### ISSUE TITLE
Service Temporarily unavailable 

### ISSUE THREAD

**Issue by 28Mochi** [TobiasDeBruijn/SkinFixer#32]
**Describe the bug**
It says Service Temporarily unavailable whenever applying skin using code.

**To Reproduce**
1. Get the code using /skin get (link)
2. Use /skin set (code)
3. It says Service temporarily unavailable (Failed to fetch UUID for the provided nickname)

**Expected behavior**
Get the skin by using the code

**Screenshots**
![image](https://user-images.githubusercontent.com/98146084/150478691-c3e86379-3823-47fd-ae90-8efa0dc04965.png)

**Version information (please complete the following information):**
 - Minecraft version: 1.18.1
 - SkinFixer version: 1.7.4
 - Operating system and OS version: Windows 10
 - Architecture: ?

**Comment by TobiasDeBruijn** [comment]
Hi there,

Thanks for brining this to my attention. It appears the SkinFixer API has broken itself. I've fixed the issue and restarted the API.
Everything *should* be fine now.

Thanks!

**Comment by 28Mochi** [comment]
Yeah it works now. My friends are celebrating in joy Thanks!

**Comment by TobiasDeBruijn** [comment]
My pleasure :D
