### ISSUE TITLE
Architecture not supported

### ISSUE THREAD

**Issue by JDtheQwerty** [TobiasDeBruijn/SkinFixer#36]
Hello! I've installed the mod, but when I am starting the server it says that my architecture is not supported. It then told me to send you a request, so... I'm here o/ My computer runs MacOS [Apple Darwin] and its arch is "aarch64." 

Thanks! Christ bless you!
<img width="944" alt="skinfixer" src="https://user-images.githubusercontent.com/105755689/168924814-9df27c0e-4915-493e-b559-b1c8cc93f124.png">

**Comment by TobiasDeBruijn** [comment]
Hey there,

Thanks for reporting this issue! At the moment MacOS aarch64 is indeed  not supported, however I'll do my best to get this support working within the next week.

Thanks!

**Comment by JDtheQwerty** [comment]
Thanks to you!

**Comment by TobiasDeBruijn** [comment]
It's been a while, apologies! I'm close to getting libraries crosscompiled for `aarch64-apple-darwin`

[https://github.com/TobiasDeBruijn/Rust-Docker-Builders/commit/3243461075bff5ed0c27855a0d79e0b7fb9ea9af](Relevant commit)

**Comment by TobiasDeBruijn** [comment]
Try this one please @JDtheQwerty: https://transfer.sh/ne2SMS/SkinFixer-1.7.7-beta.1-RELEASE.jar

**Comment by JDtheQwerty** [comment]
Thanks! :D
 Will try when possible.

God bless you!

**Comment by TobiasDeBruijn** [comment]
Awesome! I don't have an M1 macbook, or a macbook in general to test it on. Feedback is appreciated!

**Comment by JDtheQwerty** [comment]
Ok!

**Comment by JDtheQwerty** [comment]
Sorry for answering late, but unfortunately I have not tried it yet since it was for a server for my brothers and I, but the controller of one of my brothers died. So for the meanwhile we have not been able to play and try it.

**Comment by TobiasDeBruijn** [comment]
Ok. I'll close this issue for now, as I think it's fixed.

Feel free to reopen if it is not.
