### ISSUE TITLE
Error: Too Many Requests (Something went wrong fetching the UUID from Mojang.)

### ISSUE THREAD

**Issue by Daszerte** [TobiasDeBruijn/SkinFixer#37]
Describe the bug:
After launching the server, I get this error in the console (thanks to that the skins are not being loaded at all)

1. Download the plugin on a server hosted by apexminecrafthosting.com.
2. Start up the server.
3. While starting up, in the console the error appears.

Screenshots:
![skinfixer](https://user-images.githubusercontent.com/107705490/174337927-bac739db-29c8-4365-b66f-ce5aaa3206fe.PNG)

Version information:

 - Minecraft version: 1.19
 - SkinFixer version: 1.7.6
 - Windows 10

Additional info:
Most likely it's an easy fix, but I am too dumb to fix it myself...

**Comment by TobiasDeBruijn** [comment]
Hi, thanks for opening this issue! I'll increase the rate limit on the API. Please let me know if that fixes it!

**Comment by TobiasDeBruijn** [comment]
Hm, seems I dont even have rate limits. That means the error comes from upstream.

There's not much I can do about that, unfortunately. I've got some ideas but they will take some time to work out.

Please keep me posted if you keep having this issue. Thanks!

**Comment by Daszerte** [comment]
The issue has been fixed, seems like it was only temporary, thank you for the replies.

**Comment by TobiasDeBruijn** [comment]
Awesome!
