### ISSUE TITLE
Log Bug

### ISSUE THREAD

**Issue by bhhoang** [TobiasDeBruijn/SkinFixer#38]
I'm getting 2 lines like this spamming over my console

**[17:16:02 WARN]: Nag author(s): '[Dutchy76]' of 'SkinFixer' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).**

**[10:01:52 INFO]: [SkinFixer] [STDOUT] dimensionKey::getClass class net.minecraft.resources.ResourceKey**

**Comment by TobiasDeBruijn** [comment]
Fix will be released in v1.7.8, pending #36
