### ISSUE TITLE
Something went wrong applying your skin Service Temporarily Unavailable

### ISSUE THREAD

**Issue by Seija-Kijin** [TobiasDeBruijn/SkinFixer#42]
**Describe the bug**
When trying to /set skin the error message "Something went wrong applying your skin Service Temporarily Unavailable" comes up

**To Reproduce**
1. /skin get
2. /skin set 

**Expected behavior**
Skin should be set

**Screenshots**
![Error](https://user-images.githubusercontent.com/25276774/190895266-a250bd1f-6ce8-4866-aa6d-509c3930aeae.PNG)

**Version information**
 - Minecraft version: 1.19
 - SkinFixer version: 1.7.6
 - Operating system and OS version: [Same error was seen on two machines, one running Windows 11 and another on Arch Linux]
 - Architecture: 
                         --Windows 11 x64 
                         --  Arch: x86_64

**Additional context**
Same issue was also seen yesterday, waiting didn't do anything
also seems to be similar to https://github.com/TobiasDeBruijn/SkinFixer/issues/32

**Comment by TobiasDeBruijn** [comment]
Oh crap. Seems the SkinFixer API has shot itself. Will fix today!

**Comment by TobiasDeBruijn** [comment]
This should now be fixed. Please let me know if it works again for you!
