### ISSUE TITLE
Stop automatically setting skins on join

### ISSUE THREAD

**Issue by konfix** [TobiasDeBruijn/SkinFixer#46]
**Is your feature request related to a problem? Please describe.**
Yes, I've been using SkinsRestorer but I decided to switch to SkinFixer because SR doesn't work well with texture packs.
However, SkinFixer currently doesn't seem to have an option to stop applying skins on join.

**Describe the solution you'd like**
I'd like to be able to choose whether or not the skins should be applied on join. 
If you accept a texture pack download and your skin gets set at the same time, texture pack doesn't get fully downloaded. There is a simple solution, disable skin setting on join and then run a command to restore player's skin after the texture pack is downloaded (using a 3rd plugin).

Please let me know if this is possible.
Thank you!

**Comment by TobiasDeBruijn** [comment]
That should be straight forward actually!

I could also see a delay helping, if I'm changing it up anyways.

Considering doing either per user configurable, in game using a command, or globally via the config file. Would you have a preference?

**Comment by konfix** [comment]
Probably globally via the configuration, but it would be awesome anyway

**Comment by TobiasDeBruijn** [comment]
Released in v1.7.8

**Comment by konfix** [comment]
thank you!! :)
