### ISSUE TITLE
Cracked Users skin Error

### ISSUE THREAD

**Issue by hanne9** [TobiasDeBruijn/SkinFixer#48]
The mod works perfectly, but in my aternos cracked server when cracked users exit and reopen the game the plugin doesn't work correctly. These person see casual skin that aren't the skin they have. With Premium accounts there isn't this issue (Sorry for my bad english)

**Comment by TobiasDeBruijn** [comment]
Hi!

That's an interesting one. Do you see any errors in chat or console? If yes, could you attach them here?

**Comment by hanne9** [comment]
There isn't any errors in chat or errors at all

**Comment by TobiasDeBruijn** [comment]
Interesting, that sounds like a client side bug then.

I'll close this issue as solved.

**Comment by hanne9** [comment]
Ok. Thank you anyway.
