### ISSUE TITLE
1.17.1 error (Unsupported version)

### ISSUE THREAD

**Issue by marlester-dev** [TobiasDeBruijn/SkinFixer#49]
Minecraft version:
1.17.1
W
My core is patina (paper fork)
When I want to apply skin (/skin set 409606) I get this error:
https://pastebin.com/YgLZSsVm
All the plugins I have now:
 Authme, Automessage, BlockSyntax, ConsoleSpamfix, Essentials, Essentialsadddons, Forcepack, gui plugin, anti-vpn, lrx, NoCheatPlus, Permissionsex, PexTabcompleter, Protocollib, Psudocommand, SkinFixer, tab, Vault, ViaVersion

**Comment by TobiasDeBruijn** [comment]
Due to time constraints I've decided to not implement support for 1.17.1, as it is quite old by now.

However, look forward to 1.20 support.
Thanks for your patience!
