### ISSUE TITLE
update

### ISSUE THREAD

**Issue by krqte1mirapo** [TobiasDeBruijn/SkinFixer#51]
Minecraft version:1.20

**Comment by TobiasDeBruijn** [comment]
I've added 1.20 support to [BukkitReflectionUtil](https://github.com/TobiasDeBruijn/BukkitReflectionUtil/commit/8bed12bd18226375afcb956682c11673370d20dd) (which is what powers SkinFixer under the hood). I'm waiting on Spigot 1.20.1 before I'll release an update.
