### ISSUE TITLE
Poll: Database types

### ISSUE THREAD

**Issue by TobiasDeBruijn** [TobiasDeBruijn/SkinFixer#53]
If you use the database type `MYSQL`, `POSTGRES` or `SQLITE`, please leave a reply here.

I'm considering simplifying the plugin by removing these three options.

**Comment by mordisk10** [comment]
i am not currently using any of them but how is that gonna simplify the plugin and whats the idea behind it

**Comment by TobiasDeBruijn** [comment]
So the plugin currently uses a native Rust library to abstract away all supported storage types. I originally built it this way because I wanted to see if it was possible. However, it's not really nice to maintain and compiling the plugin takes ages. Furthermore, platform support is limited.

So I want to strip out this native part, and just use only Java. However, before writing a new Java 'connector' for every supported storage type, which could be quite some work, I wanted to know if its even used at all.

I don't think a full database, or sqlite is needed for what SkinFixer wants to achieve, but also don't want to remove features if there's an active userbase using it.

**Comment by mordisk10** [comment]
well i see, i am using my vote to drop the support as you said it seems like maintaining burden will eventually bring the end of the project at some point, and also later on the database types can be added back in any time.

**Comment by AAlchemy** [comment]
I'm using MYSQL. but the plugin fails to apply a skin whether i'm using DB or flat file. 
[Server] WARN The SkinFixer API returned an unexpected result: Internal Server Error

**Comment by TobiasDeBruijn** [comment]
> [Server] WARN The SkinFixer API returned an unexpected result: Internal Server Error
This has been fixed as of 2023-10-10, thanks for letting me know!

**Comment by TobiasDeBruijn** [comment]
I've rewritten the database library in v1.7.10, making maintenance MUCH easier. Closing this issue as solved.
