### ISSUE TITLE
No info on how to use on discord ?

### ISSUE THREAD

**Issue by shawn695** [TobiasDeBruijn/SkinFixer#54]
I cant seem to figure out how to use this on discord, i have the token and channel set up. i see the bot online. but nothing else and or how to use on discord

**Comment by TobiasDeBruijn** [comment]
If you've got the channel and bot set up, all you need to do is paste a skin image in the channel. The bot will then reply with a command to set the skin. An example:
![image](https://github.com/TobiasDeBruijn/SkinFixer/assets/28569170/eacd13ee-bf97-49de-a8c5-20383923d75f)
