### ISSUE TITLE
bad gateway error 

### ISSUE THREAD

**Issue by Ryunix5** [TobiasDeBruijn/SkinFixer#55]
theres an issue with the apexhosting version, it says bad gateway when i try to set the skin

**Comment by TobiasDeBruijn** [comment]
Seems to be an issue with the API. I'll need to rebuild the image, which might take some work as it's been a while, but after that it should be good to go again.

**Comment by TobiasDeBruijn** [comment]
Should be good to go again. Please let me know if you still encounter issues.
